on:
  push:
    branches:
      - "actions"
name: DeploytoSalesforceProduction
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: |
          npm install -g sfdx-cli
          #npm install gfarb/sfdx-deploy@v1

      - name: SFDX Auth
        env:
          SFDX_USERNAME: ${{ secrets.SFDX_USERNAME }}
          SFDX_PASSWORD: ${{ secrets.SFDX_PASSWORD }}
   
        run: |
            sfdx force:auth:login --username ${{ secrets.SFDX_USERNAME }} --password ${{ secrets.SFDX_PASSWORD }} --setalias DevHub
            sfdx force:org:display --json -u DevHub > sfdx-auth.json

      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: DevHub
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes
          TEST_LEVEL: RunLocalTests
          WAIT: 200
