name: Deploy to Salesforce Production
on:
  pull_request:
    types: [opened,reopened]
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: |
          npm install -g sfdx-cli
          npm install sfdx-actions/setup-sfdx@latest     
          
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.DEVHUB_SFDX_URL }}
      - name: sfdx-test-run
        run: sfdx force:apex:test:run -l RunLocalTests -w 30
